openapi: 3.1.0
info:
  title: apigo
  version: "0.1.1"
  description: >
    An application programming interface service.
  license:
    name: No License
    url: https://choosealicense.com/no-permission/
security:
  - Authorization: []
paths:
  $ref: "./paths/index.yaml"
components:
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      description: A valid authentication token with valid authorization.
  parameters:
    $ref: "./components/parameters/index.yaml"
  schemas:
    $ref: "./components/schemas/index.yaml"
  responses:
    $ref: "./components/responses/index.yaml"
tags:
  - name: account
    description: Account information and services.
  - name: resources
    description: Operations related to resources.
  - name: tags
    description: Operations related to resource tags.
  - name: user
    description: User information and services.
